- name: Install ArgoCD with Helm
  kubernetes.core.helm:
    name: argo
    chart_ref: argo/argo-cd
    create_namespace: true
    release_namespace: argo
    values:
      global:
        addPrometheusAnnotations: true
      configs:
        secret:
          ## Argo expects the password in the secret to be bcrypt hashed. You can create this hash with
          ## `htpasswd -nbBC 10 "" admin | tr -d ':\n' | sed 's/$2y/$2a/'`
          ## TODO: passwd form vault, generating in ansible
          argocdServerAdminPassword: $2a$10$wgYPV6JTAdAE6ux50hhfGeeNMroO5nMKDJy/PRO5X7UhE.2aubw0u

- name: Create Ingress for Argo
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        annotations:
          #TODO: Understand why: https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#ssl-passthrough-with-cert-manager-and-lets-encrypt
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"
          nginx.ingress.kubernetes.io/ssl-passthrough: "true"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        name: "argo"
        namespace: "argo"
      spec:
        tls:
        - hosts:
          - "argo.boredotter.dev"
          secretName: "argo-tls"
        rules:
        - host: "argo.boredotter.dev"
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: "argo-argocd-server"
                  port:
                    number: 80