- name: Debug variables from applications.yaml
  debug:
    msg: "{{ item }}"
  with_dict: "{{ types.flask }}"
  loop_control:
    loop_var: item

- name: Create local directory for rendered files
  file:
    path: "{{ playbook_dir }}/tmp/{{ item.key }}"
    state: directory
    mode: 0755
  with_dict: "{{ types.flask }}"
  loop_control:
    loop_var: item

- name: Render Kubernetes Flask Deployment
  template:
    src: "flask_runner/deployment.yaml.j2"
    dest: "{{ playbook_dir }}/tmp/{{ item.key }}/deployment-{{ item.key }}.yaml"
    mode: 0644
  with_dict: "{{ types.flask }}"
  loop_control:
    loop_var: item

- name: Render Kubernetes Flask Ingress
  template:
    src: "flask_runner/ingress.yaml.j2"
    dest: "{{ playbook_dir }}/tmp/{{ item.key }}/ingress-{{ item.key }}.yaml"
    mode: '0644'
  with_dict: "{{ types.flask }}"
  loop_control:
    loop_var: item