all:
  hosts:
    node1:
      ansible_host: 34.116.239.7
      ip: 10.240.0.10
    node2:
      ansible_host: 34.116.220.77
      ip: 10.240.0.20
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
