all:
  hosts:
    node1:
      ansible_host: 164.90.223.27
      ip: 10.114.0.3
    node2:
      ansible_host: 64.225.100.74
      ip: 10.114.0.2
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
