all:
  hosts:
    node1:
      ansible_host: 68.183.222.204
      ip: 10.114.0.2
    node2:
      ansible_host: 164.90.177.30
      ip: 10.114.0.3
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
