helm_repos:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
    
helm_deployments:
  - monitoring/namespace.yaml
  - monitoring/prometheus.yaml 
  - monitoring/promtail.yaml 
  - monitoring/loki.yaml
  - monitoring/grafana.yaml 