- name: Add Harbor Helm repository
  kubernetes.core.helm_repository:
    name: harbor
    repo_url: https://helm.goharbor.io

- name: Install Harbor with Helm
  kubernetes.core.helm:
    name: harbor
    chart_ref: harbor/harbor
    create_namespace: true
    release_namespace: harbor
    values:
      expose:
        ingress:
          hosts:
            core: harbor.test.boredotter.dev
          annotations:
            kubernetes.io/ingress.class: "nginx"
            cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        tls:
          certSource: secret
          secret:
            secretName: harbor-tls
      externalURL: https://harbor.test.boredotter.dev