- name: Add kyverno helm repo
  kubernetes.core.helm_repository:
    name: kyverno
    repo_url: https://kyverno.github.io/kyverno/

- name: Install kyverno
  kubernetes.core.helm:
    name: kyverno
    chart_ref: kyverno/kyverno
    release_namespace: kyverno
    create_namespace: true