# - name: Add Prometheus Helm repository
#   kubernetes.core.helm_repository:
#     name: prometheus-community
#     repo_url: https://prometheus-community.github.io/helm-charts

- name: Install Prometheus with Helm
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus-community/prometheus
    chart_version: 25.8.2
    release_namespace: monitoring
    values: 
      alertmanager:
        enabled: false