- name: Create local directory for rendered files
  file:
    path: "{{ playbook_dir }}/tmp/{{ item.key }}"
    state: directory
    mode: 0755
  with_dict: "{{ types.code }}"
  loop_control:
    loop_var: item

- name: Render Kubernetes Secret
  template:
    src: "code_server/secret.yaml.j2"
    dest: "{{ playbook_dir }}/tmp/{{ item.key }}/secret-{{ item.key }}.yaml"
    mode: '0644'
  with_dict: "{{ types.code }}"
  loop_control:
    loop_var: item

- name: Render Kubernetes Deployment
  template:
    src: "code_server/deployment.yaml.j2"
    dest: "{{ playbook_dir }}/tmp/{{ item.key }}/deployment-{{ item.key }}.yaml"
    mode: 0644
  with_dict: "{{ types.code }}"
  loop_control:
    loop_var: item

- name: Render Kubernetes Ingress
  template:
    src: "code_server/ingress.yaml.j2"
    dest: "{{ playbook_dir }}/tmp/{{ item.key }}/ingress-{{ item.key }}.yaml"
    mode: '0644'
  with_dict: "{{ types.code }}"
  loop_control:
    loop_var: item

- name: Apply Kubernetes Secret
  k8s:
    state: present
    src: "{{ playbook_dir }}/tmp/{{ item.key }}/secret-{{ item.key }}.yaml"
  with_dict: "{{ types.code }}"
  loop_control:
    loop_var: item

- name: Apply Kubernetes Deployment
  k8s:
    state: present
    src: "{{ playbook_dir }}/tmp/{{ item.key }}/deployment-{{ item.key }}.yaml"
  with_dict: "{{ types.code }}"
  loop_control:
    loop_var: item

- name: Apply Kubernetes Ingress
  k8s:
    state: present
    src: "{{ playbook_dir }}/tmp/{{ item.key }}/ingress-{{ item.key }}.yaml"
  with_dict: "{{ types.code }}"
  loop_control:
    loop_var: item