- name: Ensure pip is installed
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Install pre-requisites
  pip:
    name:
      - openshift
      - pyyaml
      - kubernetes
    executable: pip3