- name: Ensure pip is installed
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Install pre-requisites
  pip:
    name:
      - openshift
      - pyyaml
      - kubernetes
    executable: pip3

- name: Install helm diff plugin
  ansible.builtin.command:
    cmd: helm plugin install https://github.com/databus23/helm-diff --version v3.1.3
  args:
    creates: "/root/.local/share/helm/plugins/helm-diff"
    #The command will not be run if the specified path already exists
    #Assume that it will be enough