- name: Include vars from argo.yaml
  include_vars: argo.yaml

- name: Create Argo repositories 
  loop: "{{ argo.applications }}"
  loop_control:
    loop_var: app
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "repo-{{ app.repo_name }}"
        namespace: argo
        labels:
          argocd.argoproj.io/secret-type: repository
      stringData:
        name: "{{ app.repo_name }}"
        type: git
        url: "{{ app.git_ssh_url }}"
        sshPrivateKey: "{{ gitReposPrivateKey }}"

- name: Create Argo AppProjects
  loop: "{{ argo.applications }}"
  loop_control:
    loop_var: app
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: AppProject
      metadata:
        name: "{{ app.project }}"
        namespace: argo
      spec:
        clusterResourceWhitelist:
          - group: '*'
            kind: '*'
        destinations:
          - name: '*'
            namespace: '"{{ app.namespace }}"'
            server: https://kubernetes.default.svc
        #TODO: make namespaces in pattern {{ app.name }}-{{ env }}-* }}
        namespaceResourceWhitelist:
          - group: '*'
            kind: '*'
        sourceRepos:
          - "{{ app.git_ssh_url }}"

- name: Create Application
  loop: "{{ argo.applications }}"
  loop_control:
    loop_var: app
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: "{{ app.name }}"
        namespace: argo
      spec:
        destination:
          name: ''
          namespace: '"{{ app.namespace }}"'
          server: 'https://kubernetes.default.svc'
        source:
          path: "{{ app.manifest_source }}"
          repoURL: "{{ app.git_ssh_url }}"
          targetRevision: HEAD
          directory:
            recurse: true
        project: "{{ app.project }}"
        syncPolicy:
          automated:
            prune: false
            selfHeal: false
          retry:
            limit: 5
            backoff:
              duration: 5s
              maxDuration: 3m0s
              factor: 2
          syncOptions:
            - CreateNamespace=true