- name: Install Grafana with Helm
  kubernetes.core.helm:
    name: grafana
    chart_ref: grafana/grafana
    release_namespace: monitoring
    values:
      adminUser: BoredOtter
      adminPassword: admin
      # TODO: enable after stable dashboards
      persistence:
        type: pvc
        enabled: true
        storageClassName: local-path
      #Existing datasources like Prometheus
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus-server
          - name: Loki
            type: loki
            url: http://loki:3100
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
          - name: 'provisioned'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
      dashboards:
        provisioned:
          prometheus-stats:
            gnetId: 2
            revision: 2
            datasource: Prometheus
          node-exporter:
            gnetId: 1860
            revision: 36
            datasource: Prometheus
          logs-per-app:
            gnetId: 13639
            revision: 2
            datasource: Loki 
          nginx-next-getn:
            gnetId: 14314
            revision: 2
            datasource: Prometheus
          argo:
            gnetId: 14584
            revision: 1
            datasource: Prometheus
          kube-state-metrics:
            gnetId: 13332
            revision: 12
            datasource: Prometheus
          cert-manager:
            gnetId: 11001
            revision: 1
            datasource: Prometheus
          k8s-cluster-monitoring:
            gnetId: 315
            revision: 3
            datasource: Prometheus


- name: Create Ingress for Grafana
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        name: "grafana"
        namespace: "monitoring"
      spec:
        tls:
        - hosts:
          -  "{{ hosts.grafana }}"
          secretName: "grafana-tls"
        rules:
        - host:  "{{ hosts.grafana }}"
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: "grafana"
                  port:
                    number: 80
