- name: Install Loki with Helm
  kubernetes.core.helm:
    name: loki
    chart_ref: grafana/loki
    release_namespace: monitoring
    values:
      loki:
        auth_enabled: false #https://github.com/grafana/loki/issues/6729#issuecomment-1324208128
        commonConfig:
          replication_factor: 1
        storage:
          type: 'filesystem'
      singleBinary:
        replicas: 1
      global:
        dnsService: coredns
      gateway:
        basicauth:
          auth_enabled: false