- name: Install Loki with Helm
  kubernetes.core.helm:
    name: loki
    chart_ref: grafana/loki
    chart_version: 4.5.0 #ehh run it on latest version (6.5.0)
    release_namespace: monitoring
    values:
      deploymentMode: SingleBinary
      global:
        dnsService: coredns
      loki:
        auth_enabled: false
        commonConfig:
          replication_factor: 1
        storage:
          type: 'filesystem'
      singleBinary:
        replicas: 1