- name: Install Prometheus with Helm
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus-community/prometheus
    chart_version: 25.8.2
    release_namespace: monitoring
    values: 
      alertmanager:
        enabled: false
      prometheus-pushgateway:
        enabled: false
      prometheus-node-exporter: #TODO: figure out how to scrape ALL
        enabled: true
