all:
  hosts:
    master:
      ansible_host: 164.90.223.27
    worker-01:
      ansible_host: 64.225.100.74
  vars:
    hosts:
      grafana: grafana.boredotter.dev
      argo: argo.boredotter.dev
      harbor: harbor.boredotter.dev
      matrix: matrix.boredotter.dev
    argo:
      repositories:
        - name: meme-giver-deployment
          git_ssh_url: git@github.com:BoredOtter/meme-giver-deployment.git