all:
  hosts:
    master:
      ansible_host: 68.183.222.204
    worker-01:
      ansible_host: 164.90.177.30
  vars:
    hosts:
      grafana: grafana.boredotter.dev
      argo: argo.boredotter.dev
      harbor: harbor.boredotter.dev
      matrix: matrix.boredotter.dev
    argo:
      applications:
        - name: hms-test
          #repository settings
          repo_name: hms-manifests
          git_ssh_url: git@github.com:BoredOtter/hms-manifests.git
          #project settings
          project: hms-test
          namespace: hms-test
          manifest_source: master/

        - name: meme-giver-test
          #repository settings
          repo_name: meme-giver-deployment
          git_ssh_url: git@github.com:BoredOtter/meme-giver-deployment.git
          #project settings
          project: meme-giver-test
          namespace: meme-giver-test
          manifest_source: deployment/

        - name: custom-tools-test
          #repository settings
          repo_name: custom-images-manifests
          git_ssh_url: git@github.com:BoredOtter/custom-images-manifests.git
          #project settings
          project: custom-tools-test
          namespace: custom-tools-test
          manifest_source: manifests/