all:
  hosts:
    master:
      ansible_host: 164.90.223.27
    worker-01:
      ansible_host: 64.225.100.74
  vars:
    # users:
    #   - name: es
    #     ssh_key: #TODO
    #   - name: olszak
    #     ssh_key: #TODO
    gha_repos:
      - meme-giver
      - quotes-app