- name: Setup Cluster
  hosts: master
  become: yes
  roles:
    - k8s_dependencies
    - cluster_issuer
    #- harbor #TODO: fix crashloopbackoff 
    #- kyverno #TODO: is it worth it?
    - monitoring #TODO: make into seperate roles?
    - argo
    - sonarqube
    - trivy-operator