- name: Setup Cluster
  hosts: master
  become: yes
  roles:
    - k8s_dependencies
    - cluster_issuer
    - harbor
    #- kyverno #TODO: is it worth it?
    - monitoring #TODO: make into seperate roles?
    - argo