- name: Add Grafana Helm repository
  community.kubernetes.helm_repository:
    name: grafana
    repo_url: https://grafana.github.io/helm-charts

- name: Add Prometheus Helm repository
  community.kubernetes.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Add Elastic Helm repository
  community.kubernetes.helm_repository:
    name: elastic
    repo_url: https://helm.elastic.co

- name: Add ArgoCD Helm repository
  community.kubernetes.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: Install Harbor with Helm
  community.kubernetes.helm:
    name: harbor
    chart_ref: harbor/harbor
    create_namespace: true
    release_namespace: harbor
    values:
      expose:
        ingress:
          hosts:
            core: harbor.test.boredotter.dev
          annotations:
            kubernetes.io/ingress.class: "nginx"
            cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        tls:
          certSource: secret
          secret:
            secretName: harbor-tls
      externalURL: https://harbor.test.boredotter.dev

- name: Crete monitoring namespace
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: monitoring
        labels:
          name: monitoring

- name: Install Prometheus with Helm
  community.kubernetes.helm:
    name: prometheus
    chart_ref: prometheus-community/prometheus
    chart_version: 25.8.2
    release_namespace: monitoring

- name: Install Grafana with Helm
  community.kubernetes.helm:
    name: grafana
    chart_ref: grafana/grafana
    release_namespace: monitoring

- name: Create Ingress for Grafana
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        name: "grafana"
        namespace: "monitoring"
      spec:
        tls:
        - hosts:
          - "grafana.boredotter.dev"
          secretName: "grafana-tls"
        rules:
        - host: "grafana.boredotter.dev"
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: "grafana"
                  port:
                    number: 80

- name: Install ArgoCD with Helm
  community.kubernetes.helm:
    name: argo
    chart_ref: argo/argo-cd
    create_namespace: true
    release_namespace: argo
    #Commented out due to line 116
    # values:
    #   server:
    #     extraArgs:
    #       - --insecure #TODO: Use certs generated by Cert Manager

- name: Create Ingress for Argo
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        annotations:
          #TODO: Understand why: https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#ssl-passthrough-with-cert-manager-and-lets-encrypt
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"
          nginx.ingress.kubernetes.io/ssl-passthrough: "true"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        name: "argo"
        namespace: "argo"
      spec:
        tls:
        - hosts:
          - "argo.boredotter.dev"
          secretName: "argo-tls"
        rules:
        - host: "argo.boredotter.dev"
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: "argo-argocd-server"
                  port:
                    number: 80