- name: Run Helm Deployments
  include_tasks: "{{ item }}"
  loop:
    - kyverno/main.yaml #TODO: FIX
    - monitoring/namespace.yaml
    - monitoring/prometheus.yaml 
    - monitoring/promtail.yaml 
    - monitoring/loki.yaml
    - monitoring/grafana.yaml 
    - harbor/main.yaml 
    - argo/main.yaml
    - gha_runners/main.yaml
  loop_control:
    loop_var: item