- name: Run Helm Deployments
  include_tasks: "{{ item }}"
  loop:
    - misc/namespace.yaml
    - monitoring/prometheus.yaml 
    - monitoring/promtail.yaml 
    - monitoring/loki.yaml
    - monitoring/grafana.yaml 
    - apps/harbor.yaml 
    - apps/argo.yaml
    - apps/kyverno.yaml
  loop_control:
    loop_var: item